import { library } from '@fortawesome/fontawesome-svg-core';
// import { fab } from '@fortawesome/free-brands-svg-icons'
/*
Usage:
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
*/
import {
  faBars,
  faBomb,
  // faBookReader,
  // faCalendar,
  // faCalendarAlt,
  // faCaretDown,
  // faCaretRight,
  faCheck,
  faCode,
  faCoffee,
  // faEdit,
  faEye,
  faExclamationTriangle,
  faGavel,
  faHome,
  faInfo,
  // faLanguage,
  // faLink,
  // faLock,
  faMinusSquare,
  // faSpinner,
  // faTable,
  faThumbsUp,
  // faTimes,
  faTv,
  // faSearch,
  // faSignInAlt,
  faSignOutAlt,
  // faSort,
  // faSortDown,
  // faSortUp,
} from '@fortawesome/free-solid-svg-icons';

export default () =>
  library.add(
    faBars,
    faBomb,
    // faBookReader,
    // faCalendar,
    // faCalendarAlt,
    // faCaretDown,
    // faCaretRight,
    faCheck,
    faCode,
    faCoffee,
    // faEdit,
    faEye,
    faExclamationTriangle,
    faHome,
    faGavel,
    faInfo,
    // faLanguage,
    // faLink,
    // faLock,
    faMinusSquare,
    // faSpinner,
    // faTable,
    faThumbsUp,
    // faTimes,
    faTv,
    // faSearch,
    // faSignInAlt,
    faSignOutAlt,
    // faSort,
    // faSortDown,
    // faSortUp,
  );
